In [12]:
!curl LsSf https://astral.sh/uv/install.sh | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: LsSf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

In [13]:
!uv self update

/bin/bash: line 1: uv: command not found

In [14]:
!curl -LsSf https://astral.sh/uv/install.sh | sh
!export PATH="$HOME/.local/bin:$PATH" && uv self update

downloading uv 0.11.1 x86_64-unknown-linux-gnu
installing to /home/codespace/.local/bin
  uv
  uvx
everything's installed!
info: Checking for updates...
success: You're already on version v0.11.1 of uv (the latest version).

In [15]:
!uv self update

info: Checking for updates...
success: You're already on version v0.11.1 of uv (the latest version).

##Creating virtual enviroment
1 uv venv mienv

In [16]:
!uv pip install numpy
!uv pip install pandas

error: No virtual environment found; run `uv venv` to create an environment, or pass `--system` to install into a non-virtual environment
error: No virtual environment found; run `uv venv` to create an environment, or pass `--system` to install into a non-virtual environment

In [21]:
!source mienv/bin/activate

In [22]:
!pip install numpy
!pip install pandas

Collecting numpy
  Downloading numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Downloading numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 32.1 MB/s  0:00:00m0:00:010:01
Installing collected packages: numpy
Successfully installed numpy-2.4.3

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
Collecting pandas
  Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 23.8 MB/s  0:00:00m0:00:010:01
Installing collected packages: pandas
Successfully installed pandas-3.0.1

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [23]:
import numpy as np
import pandas as pd

In [24]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [25]:
date = pd.date_range("20230101", periods=6)
date

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[us]', freq='D')

In [30]:
df = pd.DataFrame(np.random.randn(6, 4), index=date, columns=list("ABCD"))
df

                   A         B         C         D
2023-01-01 -1.446868 -1.173861  0.399140  0.951199
2023-01-02  0.094416 -0.982727 -0.213849 -0.721973
2023-01-03  0.350875 -0.730572 -0.723131 -0.859524
2023-01-04  0.648994 -0.128364 -1.336415  1.762461
2023-01-05  0.086143 -0.652390  0.134517  0.508545
2023-01-06  0.038061 -0.041609 -0.993919 -0.399919

In [32]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20230102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2023-01-02  1.0  3   test  foo
1  1.0 2023-01-02  1.0  3  train  foo
2  1.0 2023-01-02  1.0  3   test  foo
3  1.0 2023-01-02  1.0  3  train  foo